src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[Vich\Uploadable]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $detail = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping:'articles', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 200)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 150)]
    private ?string $auteur_reference = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }


    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAuteurReference(): ?string
    {
        return $this->auteur_reference;
    }

    public function setAuteurReference(string $auteur_reference): static
    {
        $this->auteur_reference = $auteur_reference;

        return $this;
    }
}

src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Entity\Trait\SlugTrait;
use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    use SlugTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_cat = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $categoryorders = null;

    /** #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: SousCategorie::class, orphanRemoval: true)] private Collection $sousCategories; */

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'categories')]
    private ?self $parent = null;
   

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    private Collection $categories;
    
    public function __toString()
    {
        return $this->nom_cat;
    }
    public function __construct()
    {
        // $this->sousCategories = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCat(): ?string
    {
        return $this->nom_cat;
    }
    public function getCategoryorders():?int
    {
        return $this->categoryorders;
    }

    public function setCategoryorders(int $categoryorders): self
    {
        $this->categoryorders=$categoryorders;
        return $this;
    }
    public function setNomCat(string $nom_cat): static
    {
        $this->nom_cat = $nom_cat;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

   

  

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->setParent($this);
        }

        return $this;
    }

    public function removeCategory(self $category): static
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getParent() === $this) {
                $category->setParent(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use App\Repository\ArticleRepository;
use App\Repository\CategorieRepository;
use App\Repository\ProduitsRepository;
use App\Service\SearchData;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(CategorieRepository $categorieRepository,ArticleRepository $article,ProduitsRepository $products,Request $request): Response
    {
        $searchdata = new SearchData();
        $form = $this->createForm(SearchType::class,$searchdata);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            
            $nom = $searchdata->q;
            if ($nom !="") {
                $product = $products->findBy(['nom_pro'=> $nom]);  
                
                $search =[
                    'product'=> $product,
                ];
                
            }
           
            return $this->render('search/search.html.twig',[
                'form' => $form,
                'search' => $search,
            ]);
        }

        return $this->render('home/index.html.twig',[
            'categories'=>$categorieRepository->findBy([],['categoryorders'=>'asc']),
            'article'=>$article->findBy([],['id'=>'desc']),
            'produits'=>$products->findBy([],['id'=>'desc']),
            'form' => $form->createView(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
{{ parent() }}
  <div class="bg-light">
    <div class="container-fluid">
      <div class="row header_mkgm">
          <video loop muted autoplay class="video">
            <source src="{{ asset('assets/video/fond.mp4')}}" type="video/mp4">
          </video>
           <div id="header-content">
            <h2>Bienvenue sur NHPharma</h2>
            <p>Votre Santé à proximité</p>
            <a href="{{ path('app_pharmacie_index')}}" class="btn btn-outline-primary text-white">Acheter maintenant</a>
          </div>
      </div>
    </div>
  </div>

  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Catégories</h2>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container mt-5">
    <ul class="nav nav-pills mb-3 custom-pill" id="pills-tab" role="tablist">
      {% for item in categories %}
        {% if item.parent == null %}
        <li class="nav-item mt-2">
          <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-{{item.categoryorders}}" role="tab" aria-controls="pills-profile" aria-selected="true">
          {{ item.nomCat}}</a>
        </li> 
        {% endif %}    
      {% endfor %}  
    </ul>
    <div class="tab-content" id="pills-tabContent">   
      {% for item in categories %} 
        {% if item.parent == null %} 
        <div class="tab-pane fade" id="pills-{{item.categoryorders}}" role="tabpanel" aria-labelledby="pills-profile-tab">    
          <table class="table custom-table">  
            <tbody>
              {% for z in categories %}
                {% if z.parent == item.nomCat %}
                 <tr>
                  
                    <td> <a href="{{ path('categories_list',{ slug: z.slug}) }}" class="text-decoration:none;">{{ z.nomCat}}</a></td>
                  
                </tr>
                {% endif %}
              {% endfor %}
             
               
            </tbody>
          </table>
        </div>
        {% endif %}
        {% endfor %}
    </div>
  </div>
    
  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Nouveaux Produits </h2>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container mt-5">
    <div class="card-deck">
      {% for j in produits|slice(0,3) %}
      <div class="col-md-4 mt-5">
        <div class="card h-100">
          <img src="/uploads/attachments/{{j.attachment}}" class="card-img-top mkgm-img" alt="..." height="150">
            <div class="card-body">
              <h5 class="card-title">{{j.nompro}}</h5>
                {% if j.stock != 0 %}
                  <p class="text-success text-right">En stock</p>
                {% else %}
                  <p class="text-danger text-right">Stock épuissé</p>
                {% endif %}
              <p class="text-dark">{{j.prix}} XAF</p>              
            </div>
            <div class="card-footer">
              <div class="form-group row">
                <div class="col-lg-12">
                  <button class="btn btn-primary btn-lg btn-block" ><a href="{{path('app_pharmacie_detailproduit',{slug: j.slug})}}" class="text-dark">Voir les details</a></button>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-lg-12">
                  <button class="btn btn-success btn-lg btn-block" ><a href="{{path('cart_add',{id: j.id})}}" class="text-white">Ajouter au panier</a></button>
                </div>
              </div>
            </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="row align-items-center justify-content-center">
      <div class="text-center mt-5 p-t-45 align-items-center mb-2">
				<a href="{{ path('app_pharmacie_index')}}" class="btn btn-outline-success rounded">
					Voir plus
				</a>
			</div>
    </div>

  </div>






  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Conseils et Astuces du Jour</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-5">
    <div class="card-deck">
        
      {% for i in article|slice(0,3) %}
        <div class="col-md-4 mb-3 rounded mkgm_trans" data-aos="fade-up" data-aos-delay="">
          <div class="card h-100">
            <img src="/uploads/articles/{{i.image}}" class="card-img-top" alt="..." height="150">
            <div class="card-body">
              <h5 class="card-title">{{ i.titre|upper }}</h5>
              <p class="card-text text-dark">{{i.detail|slice(0,15)}} ...</p>
              <p><a href="{{path('article_detail',{slug: i.slug})}}"><button class="btn btn-success text-white">Voir plus</button></a></p>
            </div>
            <div class="card-footer">
              <small class="text-muted"><span class="icon-user-circle"></span>Auteur: {{i.auteurReference}}</small>
              <p><small> <span class="icon-date_range"></span>Créer le: {{ i.createdat|date("d/m/Y h:m:s")}}</small></p>
            </div>
          </div>
        </div>  
      {% endfor %}
    </div>
    <div class="form-group row">
        <div class="col-lg-12">
          <button class="btn btn-success btn-lg btn-block" ><a href="{{ path('article_index') }}" class="text-white">Plus D'astuces</a></button>
        </div>
      </div>

  </div>


  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="title-section text-center col-12">
          <h2 class="text-uppercase">Quelques Temoignages</h2>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12 block-3 products-wrap">
      <div class="nonloop-block-3 no-direction owl-carousel">
        <div class="testimony">
          <blockquote>
            <img src="{{ asset('assets/images/avatar_femme.jpg') }}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
              <p>&ldquo; Hey! NHPharma. suis une de vos clientes fidèles car j'ai plusieurs fois effectuée des achats sur votre site.
              J'aimerais vous exprimer ma gratitude car hier une fois de plus, vous m'avez prouvé qu'on peut encore faire confiance aux acahats
              en ligne, votre livreur a été ponctuel, poli et ma commande était bien emballé. J'ai recommandé votre site à une soeur qui est 
              souvent beaucoup occupé par le travail, elle vous contactera très bientôt. Merci de nous satisfaire&rdquo;</p>
          </blockquote>
          <p>&mdash; Kelly Holmes</p>
        </div>
        <div class="testimony">
          <blockquote>
            <img src="{{ asset('assets/images/avatar_homme.png') }}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
            <p>&ldquo; Bonjour je suis Monsieur Nathan. J'ai effectué des achats sur votre site la semaine dernière, je vous reviens pour
            exprimer mon mécontentement. En effet, j'ai passé la commande de 3 parfums homme et d'un anti grippal. Votre livreur m'a contacté et m'a dit
            qu'il fera la livraison après 30min et est bien et belle arrivé aprés 30min. J'apprécie votre professionnalisme.&rdquo;
            </p>
          </blockquote>
          <p>&mdash; Nathan Morando</p>
        </div>
        <div class="testimony">
          <blockquote>
            <img src="{{ asset('assets/images/avatar_femme.jpg') }}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
            <p>&ldquo; Bonsoir NHPharma je suis une cliente qui a fais  des achats ce matin sur votre site. J'ai été satisfait par les différentes rubriques de
            produits que vous offrez, j'ai aussi été ébloui par la beauté et l'organisation de vos différentes pages car je suis une designeuse.&rdquo;
            </p>
          </blockquote>
          <p>&mdash; Audrey Gallone</p>
        </div>
        <div class="testimony">
          <blockquote>
            <img src="{{ asset('assets/images/avatar_homme.png') }}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
            <p>&ldquo; Bonsoir je suis Monsieur Harry j'ai récemment fait un achat sur votre site de pharmacie en ligne et j'ai récemment fait un achat sur
            votre site de pharmacie en ligne et j'ai été extrêmement satisfait de mon expérience car c'était la première fois. Le processus de commande
            était simpleet rapide, et j'ai reçu ma commande dans les délais annoncés. De plus, le service client était exceptionnel. J'ai contacté l'équipe pour
            poser une question et j'ai reçu une réponse rapide et courtoise. Merci d'exiter &rdquo;
            </p>
          </blockquote>
          <p>&mdash; Harry Kameni</p>
        </div>
      </div>
    </div>
  </div>
      
      



</div>
{% endblock %}


{% block footer %}
{{ parent() }}

{% endblock %}